# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

executors:
  node-cypress:
    docker:
      - image: "cypress/browsers:node16.14.0-chrome99-ff97"

orbs:
  node: circleci/node@5
  cypress: cypress-io/cypress@2.1.0

jobs:
  test:
    docker:
      - image: cimg/node:16.16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: "yarn"
      - run:
          name: Run Unit Tests
          command: yarn run test:unit

  build:
    docker:
      - image: cimg/node:16.16
    steps:
      - checkout
      - run:
          name: Create Artifacts Directory
          command: mkdir -p /artifacts
      - node/install-packages:
          pkg-manager: "yarn"
      - run:
          name: Run Build
          command: yarn run build
      - run:
          name: Copy Build Files to Artifacts
          command: cp -r dist /artifacts
      - store_artifacts:
          path: /artifacts
          destination: build-output

workflows:
  build_workflow:
    jobs:
      - build
